ALTER TABLE SINISTREAT.SIN_REGLEMENT
 ADD (CODECLOTSINISTRE  VARCHAR2(2));

ALTER TABLE SINISTREAT.SIN_REGLEMENT
 ADD (NUMERORECOURS  DECIMAL(19));
ALTER TABLE SINISTREAT.SIN_MOUVEMENT
ADD (ID_AUDIENCE NUMBER(25));


ALTER TABLE SINISTREAT.SIN_REGLEMENT
ADD (ADRESSE_BENEF VARCHAR2(250 BYTE));


ALTER TABLE SINISTREAT.SIN_REGLEMENT
ADD (VILLE_BENEF VARCHAR2(250 BYTE));


ALTER TABLE SINISTREAT.SIN_RECOURS_AUDIENCE
ADD (ETAT_ENCOURS_AUD VARCHAR2(10 CHAR));

commit;