
package rma.notification.service.impl.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://ws.interfaces.service.notification.rma/")
public class Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private rma.notification.service.interfaces.ws.Exception faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Exception(String message, rma.notification.service.interfaces.ws.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Exception(String message, rma.notification.service.interfaces.ws.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: rma.notification.service.interfaces.ws.Exception
     */
    public rma.notification.service.interfaces.ws.Exception getFaultInfo() {
        return faultInfo;
    }

}
