
package rma.notification.service.impl.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GestionSmsWsImplService", targetNamespace = "http://ws.impl.service.notification.rma/", wsdlLocation = "https://gama.rmaassurance.com/transverse/notification/services/GestionSmsWs?WSDL")
public class GestionSmsWsImplService
    extends Service
{

    private final static URL GESTIONSMSWSIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(rma.notification.service.impl.ws.GestionSmsWsImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = rma.notification.service.impl.ws.GestionSmsWsImplService.class.getResource(".");
            url = new URL(baseUrl, "https://gama.rmaassurance.com/transverse/notification/services/GestionSmsWs?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://gama.rmaassurance.com/transverse/notification/services/GestionSmsWs?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GESTIONSMSWSIMPLSERVICE_WSDL_LOCATION = url;
    }

    public GestionSmsWsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionSmsWsImplService() {
        super(GESTIONSMSWSIMPLSERVICE_WSDL_LOCATION, new QName("http://ws.impl.service.notification.rma/", "GestionSmsWsImplService"));
    }

    /**
     * 
     * @return
     *     returns GestionSmsWs
     */
    @WebEndpoint(name = "GestionSmsWsImplPort")
    public GestionSmsWs getGestionSmsWsImplPort() {
        return super.getPort(new QName("http://ws.impl.service.notification.rma/", "GestionSmsWsImplPort"), GestionSmsWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionSmsWs
     */
    @WebEndpoint(name = "GestionSmsWsImplPort")
    public GestionSmsWs getGestionSmsWsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.impl.service.notification.rma/", "GestionSmsWsImplPort"), GestionSmsWs.class, features);
    }

}
