
package rma.notification.service.impl.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import rma.notification.service.interfaces.ws.ObjectFactory;
import rma.notification.service.interfaces.ws.SmsResponseVO;
import rma.notification.service.interfaces.ws.SmsVO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GestionSmsWs", targetNamespace = "http://ws.interfaces.service.notification.rma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GestionSmsWs {


    /**
     * 
     * @param smsVO
     * @return
     *     returns java.lang.Long
     * @throws Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "creerSms", targetNamespace = "http://ws.interfaces.service.notification.rma/", className = "rma.notification.service.interfaces.ws.CreerSms")
    @ResponseWrapper(localName = "creerSmsResponse", targetNamespace = "http://ws.interfaces.service.notification.rma/", className = "rma.notification.service.interfaces.ws.CreerSmsResponse")
    public Long creerSms(
        @WebParam(name = "smsVO", targetNamespace = "")
        SmsVO smsVO)
        throws Exception
    ;

    /**
     * 
     * @param smsVO
     * @return
     *     returns rma.notification.service.interfaces.ws.SmsResponseVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendSMSImmediate", targetNamespace = "http://ws.interfaces.service.notification.rma/", className = "rma.notification.service.interfaces.ws.SendSMSImmediate")
    @ResponseWrapper(localName = "sendSMSImmediateResponse", targetNamespace = "http://ws.interfaces.service.notification.rma/", className = "rma.notification.service.interfaces.ws.SendSMSImmediateResponse")
    public SmsResponseVO sendSMSImmediate(
        @WebParam(name = "smsVO", targetNamespace = "")
        SmsVO smsVO);

    /**
     * 
     * @param arg0
     * @return
     *     returns rma.notification.service.interfaces.ws.SmsResponseVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendSMSSchedule", targetNamespace = "http://ws.interfaces.service.notification.rma/", className = "rma.notification.service.interfaces.ws.SendSMSSchedule")
    @ResponseWrapper(localName = "sendSMSScheduleResponse", targetNamespace = "http://ws.interfaces.service.notification.rma/", className = "rma.notification.service.interfaces.ws.SendSMSScheduleResponse")
    public SmsResponseVO sendSMSSchedule(
        @WebParam(name = "arg0", targetNamespace = "")
        SmsVO arg0);

}
