-- MPS_MONDATPOSTALSINISTRE
ALTER TABLE MPS_MONDATPOSTALSINISTRE ADD (PERIODICITE VARCHAR(1)) ;

-- MPS_MONDATPOST_FILE
ALTER TABLE MPS_MONDATPOST_FILE ADD (
MNT_COMMNOTF NUMBER(10,2),
MNT_COMMMAD NUMBER(10,2),
MNTTOTAL_VIR NUMBER(10,2),
DAT_RETOUR DATE,
NBR_LIGNEREJETE NUMBER(7),
MNTREJET NUMBER(10,2),
FICHIER_RETOUR VARCHAR(100),
PERIODICITE VARCHAR(1)
) ;


-- MNouvelle table PS_ORDREVIREMENT
CREATE TABLE MPS_ORDREVIREMENT
(
  NUM_VIREMENT    NUMBER(10),
  MNT_ORDRE_VIR   NUMBER(19,2),
  TYP             VARCHAR2(10 BYTE),
  DAT_GENERATION  DATE,
  ID_FILEMP       NUMBER(19)
);

ALTER TABLE MPS_ORDREVIREMENT ADD (
  CONSTRAINT MPS_ORDREVIREMENT_PK
 PRIMARY KEY
 (NUM_VIREMENT));
 
-- MPS_MONDATPOST_FILE
ALTER TABLE MPS_SIMT modify (NOMFICHIER VARCHAR(50)) ;
ALTER TABLE MPS_SIMT ADD (
FICHIER_RETOUR VARCHAR(100),
MNTREJET NUMBER(10,2),
NBR_LIGNEREJETE NUMBER(10,2),
DAT_RETOUR DATE
) ;
commit;
-- 

